#!/bin/bash
nvcc -o main main.cu tools.cpp kernel.cu -lcublas -lcusolver -gencode arch=compute_86,code=compute_86

./main ./Data/movielens_tensor.train ./Data/movielens_tensor.test 32 3 4 50 0.004 0.05 0.01
